import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {DRACOLoader} from './vendor/DRACOLoader.js';
import {createBlankProject, normalizeProject, offsetPolygon, MATERIAL_PRESETS} from './project.mjs?v=20260930-structure-2';
import {FURNITURE_CATALOG, GROUP_LABELS, defaultFurnitureGroup, furnitureAsset} from './furniture-catalog.js';

const $ = id => document.getElementById(id);
const state = {project:null,floor:'all',room:null,selection:null,view:'3d',sectionAxis:'z',section:0,reversed:false,wallHeight:1,palette:'light',furniture:true,labels:true,walls:true,volumes:false,surfaces:true,levelMode:'stack',spaceOnly:false,walk:false,eye:1.65,yaw:0,pitch:0};
let files=[],scene,camera,renderer,controls,world,raycaster,sectionPlane,capGroup,sun,ambient,walkSaved,drag=null,toastTimer,sceneGeneration=0;
let rendered=[],pickables=[],roomLabels=[],undoStack=[],previousDisplay=null;
const furnitureDracoLoader=new DRACOLoader();
furnitureDracoLoader.setDecoderPath('./vendor/draco/');
furnitureDracoLoader.preload();
const furnitureLoader=new GLTFLoader().setDRACOLoader(furnitureDracoLoader), furnitureModelCache=new Map();
const slab=.2, edgeColor='#b37a7d';
const paletteColors={light:{wall:'#f5f4ef',floor:'#c9ad8e',furniture:'#f5f2eb',accent:'#d7d6cf'},warm:{wall:'#ede3d8',floor:'#ad8264',furniture:'#e8d2ba',accent:'#b89176'},cool:{wall:'#e8eeed',floor:'#b6bbb8',furniture:'#eff1ef',accent:'#bac8c9'}};
const materials={
  wall:new THREE.MeshStandardMaterial({color:'#f5f4ef',roughness:.86}),floor:new THREE.MeshStandardMaterial({color:'#c9ad8e',roughness:.82}),
  furniture:new THREE.MeshStandardMaterial({color:'#f5f2eb',roughness:.78}),accent:new THREE.MeshStandardMaterial({color:'#d7d6cf',roughness:.9}),
  dark:new THREE.MeshStandardMaterial({color:'#222b28',roughness:.55}),metal:new THREE.MeshStandardMaterial({color:'#aeb5b6',metalness:.78,roughness:.25}),
  glass:new THREE.MeshPhysicalMaterial({color:'#dae9e8',transparent:true,opacity:.35,roughness:.08,metalness:.1,depthWrite:false,side:THREE.DoubleSide}),
  openingHit:new THREE.MeshBasicMaterial({color:'#8fbcd6',transparent:true,opacity:.018,depthWrite:false,side:THREE.DoubleSide}),
  cut:new THREE.MeshBasicMaterial({color:edgeColor,side:THREE.DoubleSide,depthTest:true}),selected:new THREE.MeshBasicMaterial({color:'#edb77d',transparent:true,opacity:.6,depthTest:false})
};
const presetLabels={white:'白色',brick:'砖',concrete:'混凝土',wood:'木材',glass:'玻璃',metal:'金属',plaster:'石膏',tile:'瓷砖',marble:'大理石',custom:'自定义'};
const presetDefaults={white:['#f5f5f2',.75,0,1],brick:['#a66a52',.9,0,1],concrete:['#a8abad',.92,0,1],wood:['#b68b62',.7,0,1],glass:['#d9edf2',.08,.08,.34],metal:['#aeb5b6',.25,.82,1],plaster:['#ece9e2',.9,0,1],tile:['#d9dedf',.35,0,1],marble:['#e6e3df',.28,.04,1],custom:['#d8dde0',.65,0,1]};
const materialCache=new Map();
function materialFor(record,fallback='white'){const name=record?.material||fallback,base=presetDefaults[name]||presetDefaults.white,p=record?.materialProps||{},signature=`${name}|${p.color||''}|${p.roughness??''}|${p.metalness??''}|${p.opacity??''}|${p.transparent??''}`;if(materialCache.has(signature))return materialCache.get(signature);const opacity=p.opacity??base[3],transparent=Boolean(p.transparent)||name==='glass'||opacity<.99;const mat=new THREE.MeshPhysicalMaterial({color:p.color||base[0],roughness:p.roughness??base[1],metalness:p.metalness??base[2],opacity,transparent,depthWrite:!transparent,side:name==='glass'?THREE.DoubleSide:THREE.FrontSide});materialCache.set(signature,mat);return mat;}
const volumeMaterials=['#75b9ba','#d2a877','#a899d4','#a9c779','#d78f98','#80acd7','#d8c17d','#a5c1ab'].map(color=>new THREE.MeshBasicMaterial({color,transparent:true,opacity:.28,depthWrite:false,side:THREE.DoubleSide}));
const uid = prefix => `${prefix}-${Math.random().toString(36).slice(2,10)}`;
const pointDist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function pointInside(point,polygon){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const floorOf=id=>state.project.floors.find(f=>f.id===id);
const floorIndex=id=>state.project.floors.findIndex(f=>f.id===id);
const activeFloor=()=>floorOf(state.floor)||state.project.floors[0];
const selectedRecord=()=>{const s=state.selection;if(!s)return null;const f=floorOf(s.floor);return s.kind==='room'?f?.rooms.find(x=>x.id===s.id):s.kind==='wall'?f?.walls.find(x=>x.id===s.id):s.kind==='opening'?f?.walls.flatMap(w=>w.openings).find(x=>x.id===s.id):s.kind==='surface'?f?.surfaces.find(x=>x.id===s.id):f?.furniture.find(x=>x.id===s.id)};

function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600);}
const round=(n,d=2)=>Number(n).toFixed(d);
function addBox(group,x,y,z,w,h,d,material,key,name,rotation=0){const mat=typeof material==='string'?materials[material]:material;const mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.006,w),Math.max(.006,h),Math.max(.006,d)),mat);mesh.position.set(x,y+h/2,z);mesh.rotation.y=rotation;mesh.castShadow=mat!==materials.glass&&mat.transparent!==true;mesh.receiveShadow=true;mesh.userData={key,name};group.add(mesh);if(key)pickables.push(mesh);return mesh;}
function meshFloor(room,floor){const shape=new THREE.Shape();room.polygon.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:slab,bevelEnabled:false});geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,materialFor(room,'wood'));mesh.position.y=floor.elevation-slab;mesh.receiveShadow=true;mesh.userData={key:{kind:'room',floor:floor.id,id:room.id},name:room.name};return mesh;}
function slabOutline(floor){const exterior=floor.walls.filter(wall=>wall.role==='exterior'),fallback=(exterior[0]?.thickness||.2)/2;const offsets=floor.floorOutline.map((a,index)=>{const b=floor.floorOutline[(index+1)%floor.floorOutline.length];const wall=exterior.find(candidate=>(pointDist(candidate.a,a)+pointDist(candidate.b,b)<.08)||(pointDist(candidate.a,b)+pointDist(candidate.b,a)<.08));return (wall?.thickness||fallback*2)/2;});return offsetPolygon(floor.floorOutline,offsets);}
function meshSlab(floor,elevation=floor.elevation){const shape=new THREE.Shape();slabOutline(floor).forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();for(const polygon of floor.voids){const hole=new THREE.Path();polygon.forEach(([x,z],i)=>i?hole.lineTo(x,-z):hole.moveTo(x,-z));hole.closePath();shape.holes.push(hole);}const geo=new THREE.ExtrudeGeometry(shape,{depth:slab,bevelEnabled:false});geo.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geo,materials.floor);mesh.position.y=elevation-slab-.012;mesh.receiveShadow=true;return mesh;}
function meshRoomVolume(room,floor,index){const shape=new THREE.Shape();room.polygon.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:Math.max(.2,floor.height-.04),bevelEnabled:false});geometry.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geometry,volumeMaterials[index%volumeMaterials.length]);mesh.position.y=floor.elevation+.02;mesh.renderOrder=2;mesh.userData={key:{kind:'room',floor:floor.id,id:room.id},name:room.name};return mesh;}
function meshSurface(surface,floor){const shape=new THREE.Shape();surface.polygon.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:surface.thickness,bevelEnabled:false});geometry.rotateX(-Math.PI/2);const mesh=new THREE.Mesh(geometry,materialFor(surface,surface.type==='roof'?'metal':'concrete'));mesh.position.y=floor.elevation+surface.elevation-surface.thickness;mesh.rotation.z=(surface.pitch||0)*Math.PI/180;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={key:{kind:'surface',floor:floor.id,id:surface.id},name:surface.name};pickables.push(mesh);return mesh;}
function addDrainage(group,surface,floor){if(!surface.drainage||surface.polygon.length<2)return;const a=surface.polygon[0],b=surface.polygon[1],dx=b[0]-a[0],dz=b[1]-a[1],length=Math.hypot(dx,dz),angle=-Math.atan2(dz,dx),key={kind:'surface',floor:floor.id,id:surface.id};addBox(group,(a[0]+b[0])/2,floor.elevation+surface.elevation-.08,(a[1]+b[1])/2,length,.1,.12,'metal',key,'檐沟',angle);addBox(group,a[0],floor.elevation,a[1],.1,Math.max(.2,surface.elevation),.1,'metal',key,'落水管');}
function wallLocal(w){const length=pointDist(w.a,w.b),angle=-Math.atan2(w.b[1]-w.a[1],w.b[0]-w.a[0]);return {length,angle,center:[(w.a[0]+w.b[0])/2,(w.a[1]+w.b[1])/2]};}
function buildWall(group,w,floor){const {length,angle,center}=wallLocal(w),h=w.height||floor.height,key={kind:'wall',floor:floor.id,id:w.id},joinExtension=w.thickness/2;const segment=(from,to,bottom,top,mat=materialFor(w,'white'),name=w.name||'墙体',pick=key)=>{if(to-from<.012||top-bottom<.012)return;const mid=(from+to)/2-length/2;const cx=center[0]+Math.cos(-angle)*mid,cz=center[1]+Math.sin(-angle)*mid;return addBox(group,cx,floor.elevation+bottom,cz,to-from,top-bottom,w.thickness,mat,pick,name,angle);};
  if(w.type==='railing'){segment(-joinExtension,length+joinExtension,0,.05,'dark','栏杆底轨');segment(-joinExtension,length+joinExtension,.9,.95,'dark','栏杆扶手');const n=Math.max(2,Math.round(length/.16));for(let i=0;i<=n;i++)segment(length*i/n-.018,length*i/n+.018,.05,.9,'dark','栏杆立柱');return;}
  let cursor=-joinExtension;for(const o of [...w.openings].sort((a,b)=>a.start-b.start)){const start=clamp(o.start*length,0,length),end=clamp(o.end*length,start,length);segment(cursor,start,0,h);segment(start,end,0,o.bottom);segment(start,end,o.top,h);const ok={kind:'opening',floor:floor.id,id:o.id},frame=.045,frameMaterial=materialFor(o,o.type==='window'?'metal':'wood');segment(start,start+frame,o.bottom,o.top,frameMaterial,`${o.type==='window'?'窗':'门'}框`,ok);segment(end-frame,end,o.bottom,o.top,frameMaterial,'门窗框',ok);segment(start,end,o.top-frame,o.top,frameMaterial,'门窗上框',ok);if(o.type!=='door')segment(start+frame,end-frame,o.bottom+frame,o.top-frame,'glass','窗玻璃',ok);segment(start+frame,end-frame,o.bottom+frame,o.top-frame,'openingHit',`${o.type==='window'?'窗':'门'} · 点击编辑`,ok);cursor=Math.max(cursor,end);}segment(cursor,length+joinExtension,0,h);
}
function furnitureShape(group,item,floor){const y=floor.elevation,x=item.x,z=item.z,w=item.w,d=item.d,h=item.h,r=-item.rotation*Math.PI/180,key={kind:'furniture',floor:floor.id,id:item.id},g=new THREE.Group(),generation=sceneGeneration;g.position.set(x,y,z);g.rotation.y=r;group.add(g);
  const box=(bx,by,bz,bw,bh,bd,mat,name)=>addBox(g,bx,by,bz,bw,bh,bd,mat==='furniture'?materialFor(item,'white'):mat,key,name);
  const asset=furnitureAsset(item.assetId);
  if(asset){const placeholder=box(0,0,0,w,h,d,'furniture','模型载入中');let promise=furnitureModelCache.get(asset.id);if(!promise){promise=furnitureLoader.loadAsync(asset.model).then(result=>result.scene);furnitureModelCache.set(asset.id,promise);}promise.then(source=>{if(generation!==sceneGeneration)return;const model=source.clone(true),bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3());if(size.x<.0001||size.y<.0001||size.z<.0001)throw new Error('模型尺寸无效');model.scale.set(w/size.x,h/size.y,d/size.z);model.updateMatrixWorld(true);const fitted=new THREE.Box3().setFromObject(model),center=fitted.getCenter(new THREE.Vector3());model.position.set(-center.x,-fitted.min.y,-center.z);model.traverse(node=>{if(!node.isMesh)return;node.castShadow=true;node.receiveShadow=true;node.userData={...node.userData,key,name:item.name};pickables.push(node);});g.remove(placeholder);placeholder.geometry.dispose();pickables=pickables.filter(node=>node!==placeholder);g.add(model);}).catch(error=>{console.warn(`家具模型 ${asset.id} 载入失败`,error);});return;}
  if(item.type==='bed'){box(0,.08,0,w,.2,d,'furniture','床架');box(0,.28,0,w*.95,.24,d*.94,'accent','床垫');box(0,.52,d*.1,w*.9,.09,d*.6,'furniture','被褥');box(0,.14,-d*.47,w,.85,.12,'furniture','床头');for(const sx of[-.25,.25])box(w*sx,.55,-d*.32,w*.35,.15,d*.2,'furniture','枕头');}
  else if(item.type==='sofa'){box(0,.12,0,w,.28,d,'furniture','沙发底座');box(0,.3,d*.38,w,.55,d*.2,'accent','靠背');for(const sx of[-1,1])box(sx*w*.45,.3,0,w*.1,.44,d,'furniture','扶手');for(let i=0;i<Math.max(2,Math.round(w));i++){const n=Math.max(2,Math.round(w));box(-w*.4+(i+.5)*w*.8/n,.4,-d*.06,w*.76/n,.14,d*.65,'furniture','坐垫');}}
  else if(item.type==='table'){box(0,h-.08,0,w,.08,d,'furniture','桌面');for(const sx of[-1,1])for(const sz of[-1,1])box(sx*w*.4,0,sz*d*.4,.05,h-.08,.05,'metal','桌脚');}
  else if(item.type==='chair'){box(0,h*.44,0,w,.1,d,'furniture','椅座');box(0,h*.55,d*.42,w,h*.45,.07,'accent','椅背');for(const sx of[-1,1])for(const sz of[-1,1])box(sx*w*.39,0,sz*d*.39,.035,h*.44,.035,'metal','椅脚');}
  else if(item.type==='cabinet'){box(0,0,0,w,h,d,'furniture','柜体');for(const sx of[-.23,.23])box(sx*w,.12,d*.5+.012,w*.45,h-.2,.025,'accent','柜门');}
  else if(item.customBlock){const geometry=new THREE.BoxGeometry(w,h,d),faceMats=(item.faceMaterials||[]).map(material=>materialFor({material},'custom'));while(faceMats.length<6)faceMats.push(materialFor(item,'custom'));const mesh=new THREE.Mesh(geometry,faceMats);mesh.position.y=h/2;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={key,name:item.name};g.add(mesh);pickables.push(mesh);}
  else box(0,0,0,w,h,d,materialFor(item,'white'),item.name);
}
function initThree(){const host=$('canvas-host');scene=new THREE.Scene();scene.background=new THREE.Color('#cfd3d5');world=new THREE.Group();scene.add(world);const grid=new THREE.GridHelper(200,200,'#929a9e','#b8bdc0');grid.position.y=-.025;grid.material.transparent=true;grid.material.opacity=.62;grid.material.depthWrite=false;scene.add(grid);capGroup=new THREE.Group();scene.add(capGroup);camera=new THREE.PerspectiveCamera(52,1,.05,500);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#cfd3d5',1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.localClippingEnabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.28;host.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=1;controls.maxDistance=160;raycaster=new THREE.Raycaster();ambient=new THREE.HemisphereLight(0xffffff,0x697268,2.2);scene.add(ambient);sun=new THREE.DirectionalLight(0xfff4dc,3.8);sun.position.set(20,30,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;scene.add(sun);sectionPlane=new THREE.Plane(new THREE.Vector3(0,0,1),1000);window.addEventListener('resize',resize);new ResizeObserver(resize).observe(host);resize();renderer.domElement.addEventListener('pointerdown',onPointerDown);renderer.domElement.addEventListener('pointermove',onPointerMove);renderer.domElement.addEventListener('pointerup',onPointerUp);requestAnimationFrame(frame);}
function resize(){if(!renderer)return;const host=$('canvas-host'),w=host.clientWidth,h=host.clientHeight;if(w<1||h<1)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}
function frame(){requestAnimationFrame(frame);if(!renderer)return;controls.update();for(const item of roomLabels){const point=item.center.clone().project(camera);const w=$('canvas-host').clientWidth,h=$('canvas-host').clientHeight;item.button.style.left=`${(point.x*.5+.5)*w}px`;item.button.style.top=`${(-point.y*.5+.5)*h}px`;item.button.style.display=point.z<1&&Math.abs(point.x)<1&&Math.abs(point.y)<1?'':'none';}renderer.render(scene,camera);}
function clearScene(){world.traverse(obj=>{if(obj.isMesh)obj.geometry.dispose();});world.clear();capGroup.traverse(obj=>{if(obj.isMesh)obj.geometry.dispose();});capGroup.clear();rendered=[];pickables=[];roomLabels=[];$('labels').replaceChildren();}
function buildScene(focus=true){if(!state.project)return;sceneGeneration++;clearScene();const floors=state.project.floors;for(const floor of floors){const fg=new THREE.Group();fg.userData.floor=floor.id;world.add(fg);rendered.push({floor:floor.id,group:fg});const ceilingGroup=new THREE.Group();ceilingGroup.userData.ceiling=true;ceilingGroup.visible=state.walk;fg.add(ceilingGroup);const wallGroup=new THREE.Group();wallGroup.userData.walls=true;fg.add(wallGroup);const volumeGroup=new THREE.Group();volumeGroup.userData.volumes=true;fg.add(volumeGroup);const surfaceGroup=new THREE.Group();surfaceGroup.userData.surfaces=true;fg.add(surfaceGroup);if(floor.floorOutline.length>=3){fg.add(meshSlab(floor));ceilingGroup.add(meshSlab(floor,floor.elevation+floor.height+slab));}for(const surface of floor.surfaces){surfaceGroup.add(meshSurface(surface,floor));addDrainage(surfaceGroup,surface,floor);}for(const [index,room] of floor.rooms.entries()){const mesh=meshFloor(room,floor);fg.add(mesh);pickables.push(mesh);const volume=meshRoomVolume(room,floor,index);volumeGroup.add(volume);pickables.push(volume);const center=room.polygon.reduce((p,q)=>[p[0]+q[0],p[1]+q[1]],[0,0]).map(v=>v/room.polygon.length);const label=document.createElement('button');label.className='room-label';label.textContent=room.name;label.onclick=()=>select({kind:'room',floor:floor.id,id:room.id});$('labels').appendChild(label);roomLabels.push({floor:floor.id,room:room.id,center:new THREE.Vector3(center[0],floor.elevation+.15,center[1]),button:label});}for(const wall of floor.walls)buildWall(wallGroup,wall,floor);const furnitureGroup=new THREE.Group();furnitureGroup.userData.furniture=true;fg.add(furnitureGroup);for(const item of floor.furniture)furnitureShape(furnitureGroup,item,floor);}
  buildSelectionHandles();updateVisibility();updateSection();updateLabels();if(focus)focusCamera();}
function updateVisibility(){for(const row of rendered){const index=floorIndex(row.floor),all=state.floor==='all';row.group.visible=state.walk||(all?(state.levelMode!=='solo'||index===0):row.floor===state.floor);row.group.position.y=all&&state.levelMode==='explode'?index*1.8:0;const furniture=row.group.children.find(x=>x.userData.furniture),ceiling=row.group.children.find(x=>x.userData.ceiling),walls=row.group.children.find(x=>x.userData.walls),volumes=row.group.children.find(x=>x.userData.volumes),surfaces=row.group.children.find(x=>x.userData.surfaces);if(furniture)furniture.visible=state.walk||state.furniture;if(ceiling)ceiling.visible=state.walk;if(walls)walls.visible=state.walk||state.walls;if(volumes)volumes.visible=!state.walk&&state.volumes;if(surfaces)surfaces.visible=state.walk||state.surfaces;}for(const mat of volumeMaterials)mat.opacity=state.walls?.22:.43;for(const item of roomLabels){const floor=floorOf(item.floor),offset=state.floor==='all'&&state.levelMode==='explode'?floorIndex(item.floor)*1.8:0;item.center.y=floor.elevation+offset+(state.volumes&&!state.walls?floor.height*.52:.15);item.button.hidden=!state.labels||state.walk||state.floor==='all'||item.floor!==state.floor;}updateLabels();}
function updateLabels(){for(const item of roomLabels){const f=floorOf(item.floor),r=f?.rooms.find(x=>x.id===item.room);if(!r)continue;const xs=r.polygon.map(p=>p[0]),zs=r.polygon.map(p=>p[1]),size=`${round(Math.max(...xs)-Math.min(...xs),1)} × ${round(Math.max(...zs)-Math.min(...zs),1)} × ${round(f.height,1)} m`;item.button.textContent=state.volumes&&!state.walls&&state.selection?.id===r.id?`${r.name} · ${size}`:r.name;item.button.title=`${r.name} · ${size}`;}}
function focusCamera(){if(!state.project||state.walk)return;const p=state.project,floor=state.floor==='all'?null:activeFloor(),elev=floor?floor.elevation:Math.max(...p.floors.map(f=>f.elevation+f.height))/2,target=new THREE.Vector3(p.width/2,elev,p.depth/2);let size=Math.max(p.width,p.depth)*1.3;if(state.room){const room=floor?.rooms.find(r=>r.id===state.room);if(room){const xs=room.polygon.map(q=>q[0]),zs=room.polygon.map(q=>q[1]),w=Math.max(...xs)-Math.min(...xs),d=Math.max(...zs)-Math.min(...zs);target.set((Math.min(...xs)+Math.max(...xs))/2,elev,(Math.min(...zs)+Math.max(...zs))/2);size=Math.max(4,w*.95,d*.95);}}controls.target.copy(target);camera.position.set(target.x+size*.9,target.y+size*.95,target.z+size*1.15);camera.lookAt(target);controls.update();}
function setPalette(which){state.palette=which;const colors=paletteColors[which];for(const k of ['wall','floor','furniture','accent'])materials[k].color.set(colors[k]);document.querySelectorAll('[data-palette]').forEach(b=>b.classList.toggle('active',b.dataset.palette===which));}
function addCap(x,y,z,w,h,d){addBox(capGroup,x,y,z,w,h,d,'cut',null,'剖面填色');}
function updateSection(){if(!renderer||!state.project)return;capGroup.clear();if(state.walk){renderer.clippingPlanes=[];return;}if(state.floor!=='all'){const f=activeFloor();$('wall-height-value').value=`${round(state.wallHeight,2)} m`;if(!state.walls&&state.volumes){renderer.clippingPlanes=[];return;}sectionPlane.set(new THREE.Vector3(0,-1,0),f.elevation+state.wallHeight);renderer.clippingPlanes=[sectionPlane];return;}if(state.section<=0){renderer.clippingPlanes=[];$('section-value').value='完整';return;}const p=state.project,axis=state.sectionAxis,limit=axis==='x'?p.width:p.depth,cut=limit*(state.section/100*.96+.02),sign=state.reversed?1:-1;sectionPlane.set(new THREE.Vector3(axis==='x'?sign:0,0,axis==='z'?sign:0),-sign*cut);renderer.clippingPlanes=[sectionPlane];$('section-value').value=`${Math.round(cut*10)/10} m`;
  for(const floor of p.floors){for(const wall of floor.walls){if(!state.walls||wall.type==='railing')continue;const c1=axis==='x'?wall.a[0]:wall.a[1],c2=axis==='x'?wall.b[0]:wall.b[1];if((c1-cut)*(c2-cut)>0||Math.abs(c1-c2)<.001)continue;const t=(cut-c1)/(c2-c1),other=axis==='x'?wall.a[1]+(wall.b[1]-wall.a[1])*t:wall.a[0]+(wall.b[0]-wall.a[0])*t;if(axis==='x')addCap(cut,floor.elevation,other,.012,floor.height,wall.thickness);else addCap(other,floor.elevation,cut,wall.thickness,floor.height,.012);}
    const cross=[];for(const polygon of [floor.floorOutline,...floor.voids])polygon.forEach((a,i)=>{const b=polygon[(i+1)%polygon.length],ca=axis==='x'?a[0]:a[1],cb=axis==='x'?b[0]:b[1];if((ca<=cut&&cb>cut)||(cb<=cut&&ca>cut)){const t=(cut-ca)/(cb-ca);cross.push(axis==='x'?a[1]+(b[1]-a[1])*t:a[0]+(b[0]-a[0])*t);}});cross.sort((a,b)=>a-b);for(let i=0;i+1<cross.length;i+=2){const mid=(cross[i]+cross[i+1])/2,len=cross[i+1]-cross[i];if(axis==='x')addCap(cut,floor.elevation-slab,mid,.014,slab,len);else addCap(mid,floor.elevation-slab,cut,len,slab,.014);}}
}
function setFloor(id){state.floor=id;state.room=null;state.selection=null;state.walk=false;document.body.classList.remove('walk-mode');$('walk-panel').hidden=true;document.querySelectorAll('#floor-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.floor===id));const f=activeFloor();$('floor-heading').textContent=id==='all'?'全部空间':f.name;$('floor-subtitle').textContent=id==='all'?`${state.project.floors.length} 层 · ${state.project.floors.reduce((n,f)=>n+f.rooms.length,0)} 个空间`:`${f.rooms.length} 个空间 · 净高 ${round(f.height,1)} m`;$('scene-kicker').textContent=id==='all'?'WHOLE MODEL':`${f.name} · FLOOR VIEW`;$('scene-title').textContent=id==='all'?'模型总览':f.name;$('scene-meta').textContent=id==='all'?'横向与竖向剖面可调节':`室内净高 ${round(f.height,1)} m · 楼板 0.20 m`;state.wallHeight=Math.min(state.wallHeight,f.height);$('wall-height').max=f.height;$('wall-height').value=state.wallHeight;renderRoomList();renderInspector();updateVisibility();updateSection();if(state.view==='top')setView('top');else focusCamera();}
function renderFloorTabs(){const root=$('floor-tabs');root.replaceChildren();const add=(id,name)=>{const b=document.createElement('button');b.dataset.floor=id;b.textContent=name;b.onclick=()=>setFloor(id);root.appendChild(b);};add('all','全楼');state.project.floors.forEach(f=>add(f.id,f.name));}
function renderRoomList(){const root=$('room-list');root.replaceChildren();if(state.floor==='all'){for(const floor of state.project.floors){const b=document.createElement('button');b.textContent=`⌂  ${floor.name} · ${floor.rooms.length} 个空间`;b.onclick=()=>setFloor(floor.id);root.appendChild(b);}return;}activeFloor().rooms.forEach((room,i)=>{const b=document.createElement('button');b.classList.toggle('active',state.room===room.id);const label=document.createElement('span');label.textContent=`◫  ${room.name}`;const index=document.createElement('span');index.className='room-index';index.textContent=String(i+1).padStart(2,'0');b.append(label,index);b.onclick=()=>{state.room=room.id;select({kind:'room',floor:state.floor,id:room.id});renderRoomList();focusCamera();};root.appendChild(b);});}
function select(s){state.selection=s;if(s?.floor&&state.floor!==s.floor)setFloor(s.floor);state.selection=s;const item=selectedRecord();if(s?.kind==='room')state.room=s.id;renderInspector();renderRoomList();if(renderer)buildScene(false);$('scene-title').textContent=item?.name||activeFloor().name;}
function mutate(callback){undoStack.push(structuredClone(state.project));if(undoStack.length>30)undoStack.shift();callback();state.project=normalizeProject(state.project);scheduleSave();buildScene(false);renderRoomList();renderInspector();const room=activeFloor()?.rooms.find(r=>r.id===state.room);$('scene-title').textContent=room?.name||(state.floor==='all'?'模型总览':activeFloor().name);}
function updateRoomFloorForWall(floor,oldWall,newWall){for(const room of floor.rooms){room.polygon=room.polygon.map(p=>{if(pointDist(p,oldWall.a)<.28)return [...newWall.a];if(pointDist(p,oldWall.b)<.28)return [...newWall.b];return p;});}}

function buildSelectionHandles(){const s=state.selection,item=selectedRecord();if(!s||!item)return;const floor=floorOf(s.floor),handle=(x,z,role)=>{const sphere=new THREE.Mesh(new THREE.SphereGeometry(.115,14,10),materials.selected);sphere.position.set(x,floor.elevation+.16,z);sphere.renderOrder=10;sphere.userData.key={kind:'handle',floor:s.floor,id:s.id,role,targetKind:s.kind};world.add(sphere);pickables.push(sphere);};
  if(s.kind==='wall'&&item.role!=='exterior'&&state.walls){handle(...item.a,'start');handle(...item.b,'end');handle((item.a[0]+item.b[0])/2,(item.a[1]+item.b[1])/2,'move');}
  if(s.kind==='furniture'){handle(item.x,item.z,'move');handle(item.x+item.w/2,item.z+item.d/2,'resize');}
  if(s.kind==='opening'){const wall=floor.walls.find(w=>w.openings.some(o=>o.id===s.id));if(wall){const at=t=>[wall.a[0]+(wall.b[0]-wall.a[0])*t,wall.a[1]+(wall.b[1]-wall.a[1])*t];handle(...at(item.start),'start');handle(...at(item.end),'end');handle(...at((item.start+item.end)/2),'move');}}
  if(s.kind==='room')for(const [i,p] of item.polygon.entries())handle(...p,`vertex-${i}`);
  if(s.kind==='surface')for(const [i,p] of item.polygon.entries())handle(...p,`vertex-${i}`);
}
function field(container,label,value,change,{type='number',step='.01',min=null,max=null,full=false}={}){const wrap=document.createElement('label');if(full)wrap.className='full';wrap.textContent=label;const input=document.createElement('input');input.type=type;input.value=value;if(type==='number'){input.step=step;if(min!==null)input.min=min;if(max!==null)input.max=max;}input.addEventListener('change',()=>change(type==='number'?Number(input.value):input.value));wrap.appendChild(input);container.appendChild(wrap);return input;}
function selectField(container,label,value,options,change){const wrap=document.createElement('label');wrap.className='full';wrap.textContent=label;const select=document.createElement('select');for(const [v,title] of options){const option=document.createElement('option');option.value=v;option.textContent=title;select.appendChild(option);}select.value=value;select.onchange=()=>change(select.value);wrap.appendChild(select);container.appendChild(wrap);}
function materialFields(container,item){selectField(container,'材质预设',item.material||'white',MATERIAL_PRESETS.map(key=>[key,presetLabels[key]]),value=>mutate(()=>{item.material=value;const base=presetDefaults[value];item.materialProps={color:base[0],roughness:base[1],metalness:base[2],opacity:base[3],transparent:value==='glass'};}));const props=item.materialProps||{};field(container,'颜色',props.color||presetDefaults[item.material||'white'][0],value=>mutate(()=>item.materialProps.color=value),{type:'color'});field(container,'粗糙度',round(props.roughness??.72),value=>mutate(()=>item.materialProps.roughness=clamp(value,0,1)),{min:0,max:1});field(container,'金属度',round(props.metalness??0),value=>mutate(()=>item.materialProps.metalness=clamp(value,0,1)),{min:0,max:1});field(container,'透明度',round(props.opacity??1),value=>mutate(()=>{item.materialProps.opacity=clamp(value,.05,1);item.materialProps.transparent=item.materialProps.opacity<.99;}),{min:.05,max:1});}
function polygonMetrics(polygon){const area=Math.abs(polygon.reduce((sum,p,i)=>{const q=polygon[(i+1)%polygon.length];return sum+p[0]*q[1]-q[0]*p[1];},0))/2,perimeter=polygon.reduce((sum,p,i)=>sum+pointDist(p,polygon[(i+1)%polygon.length]),0),compactness=perimeter?4*Math.PI*area/(perimeter*perimeter):0;return {area,perimeter,compactness,shape:polygon.length===4&&compactness>.65?'近似矩形':'不规则多边形'};}
function renderFurnitureCatalog(container,item){const group=item.catalogGroup||defaultFurnitureGroup(item.type),assets=FURNITURE_CATALOG.filter(asset=>asset.group===group),section=document.createElement('section');section.className='furniture-catalog full';const header=document.createElement('div');header.className='catalog-heading';header.innerHTML=`<span>同类家具替换</span><small>${GROUP_LABELS[group]||'家具'} · ${assets.length} 款</small>`;section.appendChild(header);const grid=document.createElement('div');grid.className='catalog-grid';const basic=document.createElement('button');basic.type='button';basic.className=`catalog-card catalog-basic ${item.assetId?'':'active'}`;basic.innerHTML='<span class="catalog-placeholder">基础</span><b>基础造型</b>';basic.onclick=()=>{const record=selectedRecord();mutate(()=>{record.assetId=null;record.catalogGroup=defaultFurnitureGroup(record.type);});toast('已恢复基础家具造型');};grid.appendChild(basic);for(const asset of assets){const card=document.createElement('button');card.type='button';card.className=`catalog-card ${item.assetId===asset.id?'active':''}`;const image=document.createElement('img');image.src=asset.thumbnail;image.alt=asset.name;image.loading='lazy';image.onerror=()=>{const fallback=document.createElement('span');fallback.className='catalog-placeholder';fallback.textContent='3D';image.replaceWith(fallback);};const label=document.createElement('b');label.textContent=asset.name;card.append(image,label);card.onclick=()=>{const record=selectedRecord();if(!record)return;mutate(()=>{record.assetId=asset.id;record.catalogGroup=asset.group;record.type=asset.type;record.name=asset.name;});toast(`已替换为 ${asset.name}，位置与尺寸保持不变`);};grid.appendChild(card);}section.appendChild(grid);container.appendChild(section);}
function renderInspector(){const root=$('selection-fields'),item=selectedRecord(),s=state.selection;root.replaceChildren();$('selection-fields').hidden=!item;$('selection-actions').hidden=!item;$('inspector-empty').hidden=!!item;$('delete-selected').disabled=!!(item&&s.kind==='wall'&&(item.role==='exterior'||item.construction==='filled'));$('delete-selected').textContent=item&&s.kind==='opening'?`删除${item.type==='door'?'门':'窗'}`:'删除';if(!item){$('selection-title').textContent='选择构件';$('selection-help').textContent='外墙轮廓锁定；门窗可直接点击选择、编辑或删除。打开空间体块后可关闭墙面，核对空间尺寸。';return;}
  $('selection-title').textContent=item.name||({room:'空间',wall:'墙体',opening:'门窗',furniture:'家具',surface:'楼板屋面'}[s.kind]);$('selection-help').textContent=s.kind==='wall'?(item.role==='exterior'?'外墙轮廓已锁定；厚度、高度、材质和门窗仍可编辑。':item.construction==='filled'?'图纸实墙已建模；如需拆除，先改为可拆内墙。':'可拆内墙：可移动、伸缩或删除。'):{room:'修改名称、边界与地面材质，并查看形状分析。',opening:'拖动两端调整开口宽度；可设置开启与铰链方向。',furniture:'拖动中心移动，角点缩放；自动限制在空间边界内。',surface:'编辑楼板、吊顶、屋面或带排水的雨棚。'}[s.kind];
  if(s.kind==='room'){field(root,'空间名称',item.name,v=>mutate(()=>{item.name=v||'未命名';}),{type:'text',full:true});const xs=item.polygon.map(p=>p[0]),zs=item.polygon.map(p=>p[1]),m=polygonMetrics(item.polygon);const note=document.createElement('div');note.className='readonly';note.textContent=`${m.shape} · ${item.polygon.length} 个顶点 · 长 ${round(Math.max(...xs)-Math.min(...xs))} × 宽 ${round(Math.max(...zs)-Math.min(...zs))} × 高 ${round(floorOf(s.floor).height)} m · 面积 ${round(m.area)} ㎡ · 周长 ${round(m.perimeter)} m`;root.appendChild(note);materialFields(root,item);}
  if(s.kind==='wall'){field(root,'名称',item.name||'墙体',v=>mutate(()=>item.name=v),{type:'text',full:true});const note=document.createElement('div');note.className='readonly';note.textContent=`${item.role==='exterior'?'外墙 · 轮廓锁定':item.construction==='filled'?'图纸填充实墙':'可拆内墙'} · 长 ${round(pointDist(item.a,item.b))} m`;root.appendChild(note);if(item.role!=='exterior'){selectField(root,'内墙依据',item.construction,[['filled','图纸填充实墙'],['inferred','可拆内墙']],v=>mutate(()=>item.construction=v));selectField(root,'类型',item.type,[['wall','墙体'],['railing','栏杆']],v=>mutate(()=>item.type=v));for(const [name,key,index] of [['起点 X','a',0],['起点 Y','a',1],['终点 X','b',0],['终点 Y','b',1]])field(root,name,round(item[key][index]),v=>mutate(()=>{const old=structuredClone(item);item[key][index]=clamp(Math.round(v*2)/2,0,index?state.project.depth:state.project.width);updateRoomFloorForWall(floorOf(s.floor),old,item);}),{min:0,step:'.5'});}field(root,'墙厚 m',round(item.thickness),v=>mutate(()=>item.thickness=clamp(v,.06,.8)),{min:.06,max:.8});field(root,'墙高 m',round(item.height||floorOf(s.floor).height),v=>mutate(()=>item.height=clamp(v,.4,8)),{min:.4,max:8});materialFields(root,item);const add=document.createElement('button');add.textContent='＋ 在此墙添加门或窗';add.className='full';add.onclick=()=>{mutate(()=>item.openings.push({id:uid('opening'),type:'door',start:.35,end:.65,bottom:0,top:2.15,hinge:'left',swing:'inward',material:'white'}));select({kind:'opening',floor:s.floor,id:item.openings.at(-1).id});};root.appendChild(add);}
  if(s.kind==='opening'){const wall=floorOf(s.floor).walls.find(w=>w.openings.some(o=>o.id===s.id)),length=pointDist(wall.a,wall.b);selectField(root,'开口类型',item.type,[['door','门'],['window','窗'],['full','落地窗']],v=>mutate(()=>{const original=wall.openings.find(o=>o.id===s.id);original.type=v;original.bottom=v==='window'?.9:0;}));const note=document.createElement('div');note.className='readonly';note.textContent=`宽 ${round((item.end-item.start)*length)} m × 高 ${round(item.top-item.bottom)} m`;root.appendChild(note);selectField(root,'铰链侧',item.hinge||'left',[['left','左侧'],['right','右侧']],v=>mutate(()=>item.hinge=v));selectField(root,'开启方式',item.swing||'inward',[['inward','向内'],['outward','向外'],['slide','推拉']],v=>mutate(()=>item.swing=v));field(root,'起点 %',round(item.start*100,0),v=>mutate(()=>wall.openings.find(o=>o.id===s.id).start=clamp(v/100,0,item.end-.04)),{min:0,max:100});field(root,'终点 %',round(item.end*100,0),v=>mutate(()=>wall.openings.find(o=>o.id===s.id).end=clamp(v/100,item.start+.04,1)),{min:0,max:100});field(root,'窗台高 m',round(item.bottom),v=>mutate(()=>wall.openings.find(o=>o.id===s.id).bottom=clamp(v,0,item.top-.35)),{min:0});field(root,'开口顶高 m',round(item.top),v=>mutate(()=>wall.openings.find(o=>o.id===s.id).top=clamp(v,item.bottom+.35,floorOf(s.floor).height)),{min:.4});materialFields(root,item);}
  if(s.kind==='furniture'){field(root,'名称',item.name,v=>mutate(()=>item.name=v||'家具'),{type:'text',full:true});selectField(root,'家具类型',item.type,[['bed','床'],['sofa','沙发'],['table','桌'],['chair','椅'],['cabinet','柜'],['other','其他']],v=>mutate(()=>{item.type=v;item.assetId=null;item.catalogGroup=defaultFurnitureGroup(v);}));for(const [label,key,max] of [['位置 X','x',state.project.width],['位置 Y','z',state.project.depth],['长 m','w',10],['宽 m','d',10],['高 m','h',5]])field(root,label,round(item[key]),v=>mutate(()=>item[key]=clamp(v,key==='x'||key==='z'?0:.1,max)),{min:0,max});field(root,'旋转角度 °',round(item.rotation,0),v=>mutate(()=>item.rotation=v%360),{step:'1'});materialFields(root,item);if(item.customBlock){selectField(root,'网格编辑模式',item.editMode||'object',[['object','对象'],['face','面'],['edge','边'],['loop','环线']],v=>mutate(()=>item.editMode=v));field(root,'选中面 1–6',(item.selectedFace||0)+1,v=>mutate(()=>item.selectedFace=clamp(Math.round(v)-1,0,5)),{min:1,max:6,step:'1'});selectField(root,'选中面材质',item.faceMaterials?.[item.selectedFace||0]||'custom',MATERIAL_PRESETS.map(key=>[key,presetLabels[key]]),v=>mutate(()=>item.faceMaterials[item.selectedFace||0]=v));}if(item.catalogGroup==='lighting'||/灯|lamp|light/i.test(item.name)){selectField(root,'灯光状态',item.lightOn?'on':'off',[['on','开启'],['off','关闭']],v=>mutate(()=>item.lightOn=v==='on'));field(root,'亮度',round(item.brightness??.8),v=>mutate(()=>item.brightness=clamp(v,0,1)),{min:0,max:1});}if(!item.customBlock)renderFurnitureCatalog(root,item);}
  if(s.kind==='surface'){field(root,'名称',item.name,v=>mutate(()=>item.name=v||'结构构件'),{type:'text',full:true});selectField(root,'构件类型',item.type,[['slab','楼板'],['ceiling','吊顶'],['roof','屋面'],['leanTo','雨棚']],v=>mutate(()=>item.type=v));field(root,'标高 m',round(item.elevation),v=>mutate(()=>item.elevation=clamp(v,-.5,floorOf(s.floor).height+5)),{min:-.5,max:13});field(root,'厚度 m',round(item.thickness),v=>mutate(()=>item.thickness=clamp(v,.04,1)),{min:.04,max:1});field(root,'坡度 °',round(item.pitch,0),v=>mutate(()=>item.pitch=clamp(v,-60,60)),{min:-60,max:60,step:'1'});selectField(root,'檐沟与落水管',item.drainage?'on':'off',[['on','生成'],['off','关闭']],v=>mutate(()=>item.drainage=v==='on'));materialFields(root,item);}
}
function undo(){const last=undoStack.pop();if(!last){toast('暂无可撤销操作');return;}state.project=normalizeProject(last);scheduleSave();buildScene(false);renderRoomList();renderInspector();toast('已撤销');}
function removeSelected(){const s=state.selection;if(!s)return;if(s.kind==='room'&&floorOf(s.floor).rooms.length<=1){toast('每层至少保留一个空间');return;}if(s.kind==='wall'){const wall=selectedRecord();if(wall.role==='exterior'){toast('外墙轮廓已锁定，不能删除');return;}if(wall.construction==='filled'){toast('图纸填充实墙需先改为可拆内墙');return;}}mutate(()=>{const floor=floorOf(s.floor);if(s.kind==='room')floor.rooms=floor.rooms.filter(x=>x.id!==s.id);if(s.kind==='wall')floor.walls=floor.walls.filter(x=>x.id!==s.id);if(s.kind==='opening')for(const wall of floor.walls)wall.openings=wall.openings.filter(x=>x.id!==s.id);if(s.kind==='furniture')floor.furniture=floor.furniture.filter(x=>x.id!==s.id);if(s.kind==='surface')floor.surfaces=floor.surfaces.filter(x=>x.id!==s.id);state.selection=null;state.room=null;});toast('已删除');}
function canvasRay(event){const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1),camera);return raycaster;}
function groundPoint(event,floorId){canvasRay(event);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),-floorOf(floorId).elevation),hit=new THREE.Vector3();return raycaster.ray.intersectPlane(plane,hit)?[hit.x,hit.z]:null;}
function snapPoint(p,floorId,exclude){let best=p.map(value=>Math.round(value*2)/2),d=.28;for(const wall of floorOf(floorId).walls){if(wall.id===exclude)continue;for(const q of [wall.a,wall.b,[(wall.a[0]+wall.b[0])/2,(wall.a[1]+wall.b[1])/2]]){const distance=pointDist(p,q);if(distance<d){best=q;d=distance;}}}return [...best];}
function onPointerDown(event){if(state.walk)return;canvasRay(event);const hit=raycaster.intersectObjects(pickables,false).find(x=>x.object.visible&&x.object.parent?.visible);if(!hit){state.selection=null;renderInspector();return;}const key=hit.object.userData.key;if(!key)return;if(key.kind==='handle'){const p=groundPoint(event,key.floor);drag={key,start:p,original:structuredClone(state.project),record:structuredClone(selectedRecord()),last:0};controls.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);return;}select(key);}
function onPointerMove(event){if(!drag)return;const p=groundPoint(event,drag.key.floor);if(!p)return;const dx=p[0]-drag.start[0],dz=p[1]-drag.start[1],floor=floorOf(drag.key.floor),key=drag.key,record=selectedRecord(),source=drag.record;if(!record)return;const safe=(v,i)=>clamp(v,0,i?state.project.depth:state.project.width);
  if(key.targetKind==='wall'){if(record.role==='exterior')return;if(key.role==='move'){const a=snapPoint([safe(source.a[0]+dx,0),safe(source.a[1]+dz,1)],floor.id,record.id),shift=[a[0]-source.a[0],a[1]-source.a[1]];record.a=a;record.b=[safe(source.b[0]+shift[0],0),safe(source.b[1]+shift[1],1)];}else{const endpoint=key.role==='start'?'a':'b';record[endpoint]=snapPoint([safe(source[endpoint][0]+dx,0),safe(source[endpoint][1]+dz,1)],floor.id,record.id);}floor.rooms=structuredClone(drag.original.floors.find(f=>f.id===floor.id).rooms);updateRoomFloorForWall(floor,source,record);}
  if(key.targetKind==='room'){const i=Number(key.role.split('-')[1]);record.polygon[i]=snapPoint([safe(source.polygon[i][0]+dx,0),safe(source.polygon[i][1]+dz,1)],floor.id);}
  if(key.targetKind==='surface'){const i=Number(key.role.split('-')[1]);record.polygon[i]=snapPoint([safe(source.polygon[i][0]+dx,0),safe(source.polygon[i][1]+dz,1)],floor.id);}
  if(key.targetKind==='furniture'){if(key.role==='move'){const room=floor.rooms.find(r=>pointInside([source.x,source.z],r.polygon)),xs=room?.polygon.map(q=>q[0])||[0,state.project.width],zs=room?.polygon.map(q=>q[1])||[0,state.project.depth];record.x=clamp(source.x+dx,Math.min(...xs)+record.w/2,Math.max(...xs)-record.w/2);record.z=clamp(source.z+dz,Math.min(...zs)+record.d/2,Math.max(...zs)-record.d/2);const collision=floor.furniture.some(other=>other.id!==record.id&&Math.abs(other.x-record.x)<(other.w+record.w)/2&&Math.abs(other.z-record.z)<(other.d+record.d)/2);if(collision){record.x=source.x;record.z=source.z;}}else{record.w=clamp(source.w+dx,.1,10);record.d=clamp(source.d+dz,.1,10);}}
  if(key.targetKind==='opening'){const wall=floor.walls.find(w=>w.openings.some(o=>o.id===record.id)),vx=wall.b[0]-wall.a[0],vz=wall.b[1]-wall.a[1],t=(dx*vx+dz*vz)/(vx*vx+vz*vz);if(key.role==='move'){const span=source.end-source.start;record.start=clamp(source.start+t,0,1-span);record.end=record.start+span;}else if(key.role==='start')record.start=clamp(source.start+t,0,record.end-.04);else record.end=clamp(source.end+t,record.start+.04,1);}
  const now=performance.now();if(now-drag.last>45){drag.last=now;buildScene(false);renderInspector();}}
function onPointerUp(){if(!drag)return;undoStack.push(drag.original);if(undoStack.length>30)undoStack.shift();drag=null;controls.enabled=true;state.project=normalizeProject(state.project);scheduleSave();buildScene(false);renderInspector();}

function enterWalk(){if(state.floor==='all'){setFloor(state.project.floors[0].id);}const floor=activeFloor(),room=floor.rooms.find(r=>r.id===state.room)||floor.rooms[0];state.room=room.id;walkSaved={position:camera.position.clone(),target:controls.target.clone(),up:camera.up.clone(),fov:camera.fov,wallHeight:state.wallHeight};state.walk=true;state.eye=Math.min(1.65,floor.height-.2);const center=room.polygon.reduce((v,p)=>[v[0]+p[0],v[1]+p[1]],[0,0]).map(v=>v/room.polygon.length);camera.up.set(0,1,0);camera.position.set(center[0],floor.elevation+state.eye,center[1]);state.yaw=0;state.pitch=0;camera.fov=68;controls.enabled=false;document.body.classList.add('walk-mode');$('walk-panel').hidden=false;$('eye-slider').value=state.eye;updateWalkCamera();updateVisibility();updateSection();toast('已进入漫游：WASD 移动，Esc 退出');}
function exitWalk(){if(!state.walk)return;state.walk=false;controls.enabled=true;document.body.classList.remove('walk-mode');$('walk-panel').hidden=true;if(walkSaved){camera.position.copy(walkSaved.position);controls.target.copy(walkSaved.target);camera.up.copy(walkSaved.up);camera.fov=walkSaved.fov;state.wallHeight=walkSaved.wallHeight;}camera.updateProjectionMatrix();updateVisibility();updateSection();walkSaved=null;}
function updateWalkCamera(){if(!state.walk)return;const floor=activeFloor();camera.position.y=floor.elevation+state.eye;const yaw=state.yaw*Math.PI/180,pitch=state.pitch*Math.PI/180,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch));controls.target.copy(camera.position).addScaledVector(direction,3);camera.lookAt(controls.target);camera.updateProjectionMatrix();$('eye-value').value=`${round(state.eye)} m`;$('fov-value').value=`${round(camera.fov,0)}°`;$('yaw-value').value=`${round(state.yaw,0)}°`;$('pitch-value').value=`${round(state.pitch,0)}°`;}
function moveWalk(direction){if(!state.walk)return;const yaw=state.yaw*Math.PI/180,forward=[Math.sin(yaw),Math.cos(yaw)],right=[forward[1],-forward[0]];let delta=direction==='forward'?forward:direction==='back'?forward.map(v=>-v):direction==='right'?right:right.map(v=>-v);camera.position.x=clamp(camera.position.x+delta[0]*.3,.15,state.project.width-.15);camera.position.z=clamp(camera.position.z+delta[1]*.3,.15,state.project.depth-.15);updateWalkCamera();}

function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('spatial-editor-projects',1);request.onupgradeneeded=()=>request.result.createObjectStore('projects');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function storeProject(project){const database=await openDatabase();await new Promise((resolve,reject)=>{const tx=database.transaction('projects','readwrite');tx.objectStore('projects').put(project,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});database.close();}
async function loadStoredProject(){const database=await openDatabase();const result=await new Promise((resolve,reject)=>{const tx=database.transaction('projects');const request=tx.objectStore('projects').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});database.close();return result;}
let saveTimer;function scheduleSave(){clearTimeout(saveTimer);$('save-status').textContent='保存中…';saveTimer=setTimeout(async()=>{try{await storeProject(state.project);$('save-status').textContent='已自动保存到本机';}catch(error){$('save-status').textContent='自动保存失败，请导出项目 JSON';toast('本机存储空间不足，请导出项目 JSON');}},500);}
function downloadProject(){const content=JSON.stringify(state.project,null,2),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'application/json'}));link.download=`${state.project.name.replace(/[\\/:*?"<>|]/g,'_')}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);}
function openProject(raw){try{state.project=normalizeProject(raw);state.floor='all';state.room=null;state.selection=null;state.view='3d';state.walls=true;state.volumes=true;state.surfaces=true;state.furniture=true;state.levelMode='stack';state.spaceOnly=false;previousDisplay=null;syncDisplayControls();undoStack=[];$('editor-title').textContent=state.project.name;$('start-screen').hidden=true;$('editor-screen').hidden=false;if(!renderer)initThree();camera.up.set(0,1,0);document.querySelectorAll('.view-toggle button').forEach(b=>b.classList.toggle('active',b.id==='view-3d'));renderFloorTabs();buildScene();setFloor('all');scheduleSave();toast('空间模型已打开');}catch(error){toast(error.message);throw error;}}
function showPlan(floor){const tabs=$('plan-tabs');tabs.replaceChildren();for(const f of state.project.floors){const b=document.createElement('button');b.textContent=f.name;b.onclick=()=>showPlan(f.id);tabs.appendChild(b);}const selected=floorOf(floor)||state.project.floors[0];$('plan-image').hidden=!selected.sourceImage;$('plan-image').src=selected.sourceImage||'';if(!selected.sourceImage)toast('这个项目没有保存原始图纸');}
async function fileToPlan(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error(`${file.name} 不是支持的图片格式`);if(file.size>8*1024*1024)throw new Error(`${file.name} 超过 8 MB`);const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});const image=new Image();image.src=dataUrl;await image.decode();return {name:file.name,dataUrl,imageWidth:image.naturalWidth,imageHeight:image.naturalHeight};}
function renderPlanPreviews(){const previews=$('plan-previews');previews.replaceChildren();previews.hidden=!files.length;for(const [i,plan] of files.entries()){const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption'),remove=document.createElement('button');image.src=plan.dataUrl;image.alt=`第 ${i+1} 层图纸`;caption.textContent=`${i+1}F · ${plan.name}`;remove.type='button';remove.className='remove-plan';remove.textContent='×';remove.title=`删除第 ${i+1} 层图纸`;remove.setAttribute('aria-label',`删除第 ${i+1} 层图纸 ${plan.name}`);remove.onclick=event=>{event.preventDefault();event.stopPropagation();const [deleted]=files.splice(i,1);$('plan-files').value='';renderPlanPreviews();toast(`已删除 ${deleted.name}`);};figure.append(image,caption,remove);previews.appendChild(figure);}}
async function setFiles(fileList){try{files=await Promise.all([...fileList].slice(0,10).map(fileToPlan));renderPlanPreviews();toast(`已导入 ${files.length} 张图纸`);}catch(error){toast(error.message);}}
async function recognize(){if(!files.length){toast('请先上传至少一张平面图');return;}const button=$('generate');button.disabled=true;button.textContent='准备分阶段识别…';try{const width=Number($('plan-width').value)||undefined,depth=Number($('plan-depth').value)||undefined,height=Number($('floor-height').value)||3;const plans=files.map(plan=>({...plan,widthMeters:width,depthMeters:depth,floorHeight:height}));const response=await fetch('./api/recognize',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify({name:$('project-name').value,plans,floorHeight:height})});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||'当前部署未启用 AI 识别服务，请运行配套 Node 服务或先建空白空间');}if(!response.body)throw new Error('浏览器不支持分阶段识别结果');const reader=response.body.getReader(),decoder=new TextDecoder();let pending='',project=null;const event=line=>{if(!line.trim())return;const payload=JSON.parse(line);if(payload.type==='progress'){button.textContent=`${payload.floor}/${payload.total}层 · ${payload.stage}…`;$('ai-status').textContent=`正在识别：${payload.stage}（第 ${payload.floor}/${payload.total} 层）`;}if(payload.type==='error')throw new Error(payload.error);if(payload.type==='done')project=payload.project;};while(true){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});let newline;while((newline=pending.indexOf('\n'))>=0){event(pending.slice(0,newline));pending=pending.slice(newline+1);}if(done)break;}if(pending.trim())event(pending);if(!project)throw new Error('识别未返回项目数据');openProject(project);}catch(error){toast(error.message);$('ai-status').textContent=`识别失败：${error.message}`;$('ai-status').classList.add('error');}finally{button.disabled=false;button.innerHTML='识别并生成空间模型 <span>→</span>';}}
function syncDisplayControls(){$('show-walls').checked=state.walls;$('show-volumes').checked=state.volumes;$('show-surfaces').checked=state.surfaces;$('show-furniture').checked=state.furniture;$('only-spaces').classList.toggle('active',state.spaceOnly);$('level-mode').textContent={stack:'楼层叠放',explode:'楼层爆炸',solo:'单层查看'}[state.levelMode];}
function setDisplay(mode,checked){state.spaceOnly=false;previousDisplay=null;state[mode]=checked;syncDisplayControls();buildScene(false);}
function toggleOnlySpaces(){if(!state.spaceOnly){previousDisplay={walls:state.walls,volumes:state.volumes,surfaces:state.surfaces,furniture:state.furniture};state.walls=false;state.volumes=true;state.surfaces=false;state.furniture=false;state.spaceOnly=true;}else{Object.assign(state,previousDisplay||{walls:true,volumes:true,surfaces:true,furniture:true});state.spaceOnly=false;previousDisplay=null;}syncDisplayControls();buildScene(false);}
async function checkAi(){try{const response=await fetch('./api/status');if(!response.ok)throw new Error('AI service unavailable');const status=await response.json();$('ai-status').textContent=status.aiReady?`AI 识别已就绪 · ${status.model}`:'AI 识别未配置。可先建空白空间，或按说明设置 INFERERA_API_KEY。';$('ai-status').classList.toggle('error',!status.aiReady);}catch{$('ai-status').textContent='在线静态版可建空白空间或导入项目；AI 识别需运行配套服务';$('ai-status').classList.add('error');}}
async function showContinue(){try{const previous=await loadStoredProject();if(!previous)return;const button=document.createElement('button');button.textContent=`继续上次项目：${previous.name}`;button.onclick=()=>openProject(previous);document.querySelector('.import-alternatives').appendChild(button);}catch{}}

function addRoom(){if(state.floor==='all')setFloor(state.project.floors[0].id);const floor=activeFloor(),p=state.project,x=clamp(p.width/2,1,p.width-1),z=clamp(p.depth/2,1,p.depth-1),w=Math.min(3,p.width*.35),d=Math.min(3,p.depth*.35),id=uid('room');mutate(()=>{floor.rooms.push({id,name:`未命名${floor.rooms.length+1}`,polygon:[[x-w/2,z-d/2],[x+w/2,z-d/2],[x+w/2,z+d/2],[x-w/2,z+d/2]]});state.selection={kind:'room',floor:floor.id,id};});toast('空间已添加，拖动顶点可调整范围');}
function addWall(){if(state.floor==='all')setFloor(state.project.floors[0].id);const floor=activeFloor(),p=state.project,id=uid('wall');mutate(()=>{floor.walls.push({id,name:'可拆内墙',a:[p.width*.35,p.depth*.5],b:[p.width*.65,p.depth*.5],thickness:.18,type:'wall',role:'interior',construction:'inferred',openings:[]});state.selection={kind:'wall',floor:floor.id,id};});toast('可拆内墙已添加');}
function addFurniture(){if(state.floor==='all')setFloor(state.project.floors[0].id);const floor=activeFloor(),p=state.project,id=uid('furniture');mutate(()=>{floor.furniture.push({id,name:'新家具',type:'chair',x:p.width/2,z:p.depth/2,w:.55,d:.55,h:.9,rotation:0});state.selection={kind:'furniture',floor:floor.id,id};});toast('家具已添加，可在右侧选择类型');}
function addSurface(type){if(state.floor==='all')setFloor(state.project.floors[0].id);const floor=activeFloor(),p=state.project,id=uid('surface'),margin=Math.min(1,Math.min(p.width,p.depth)*.08),polygon=[[margin,margin],[p.width-margin,margin],[p.width-margin,p.depth-margin],[margin,p.depth-margin]],labels={slab:'新楼板',ceiling:'新吊顶',roof:'新屋面',leanTo:'新雨棚'};mutate(()=>{floor.surfaces.push({id,name:labels[type],type,polygon,elevation:type==='slab'?0:floor.height,thickness:.2,pitch:type==='roof'||type==='leanTo'?12:0,drainage:type==='leanTo',material:type==='roof'?'metal':'concrete'});state.selection={kind:'surface',floor:floor.id,id};});toast(`${labels[type]}已添加，可拖动顶点修改轮廓`);}
function addBlock(){if(state.floor==='all')setFloor(state.project.floors[0].id);const floor=activeFloor(),p=state.project,id=uid('furniture');mutate(()=>{floor.furniture.push({id,name:'自定义体块',type:'other',x:p.width/2,z:p.depth/2,w:1.2,d:1.2,h:1.2,rotation:0,material:'custom',customBlock:true,editMode:'object',selectedFace:0,faceMaterials:Array(6).fill('custom')});state.selection={kind:'furniture',floor:floor.id,id};});toast('自定义体块已添加，可切换对象、面、边与环线编辑');}
function toggleLevelMode(){state.levelMode=state.levelMode==='stack'?'explode':state.levelMode==='explode'?'solo':'stack';syncDisplayControls();updateVisibility();focusCamera();toast({stack:'已恢复楼层叠放',explode:'已展开楼层',solo:'当前显示第一层，可用顶部楼层标签切换'}[state.levelMode]);}
function startBlank(){const width=clamp(Number($('plan-width').value)||10,2,100),height=clamp(Number($('floor-height').value)||3,2,8),depth=clamp(Number($('plan-depth').value)||(files[0]?width*files[0].imageHeight/files[0].imageWidth:width*.8),2,100),p=createBlankProject($('project-name').value||'未命名项目',width,depth,height);if(files.length){const first=p.floors[0];first.sourceImage=files[0].dataUrl;for(let i=1;i<files.length;i++){const copy=structuredClone(first);copy.id=`floor-${i+1}`;copy.name=`${i+1}层`;copy.elevation=i*(height+slab);copy.sourceImage=files[i].dataUrl;copy.rooms[0].id=`room-${i+1}`;copy.walls.forEach((wall,wi)=>wall.id=`wall-${i+1}-${wi+1}`);p.floors.push(copy);}}openProject(p);}
function setView(view){state.view=view;document.querySelectorAll('.view-toggle button').forEach(b=>b.classList.toggle('active',b.id===`view-${view}`));if(view==='top'){const p=state.project,target=new THREE.Vector3(p.width/2,state.floor==='all'?p.floors.at(-1).elevation:activeFloor().elevation,p.depth/2);controls.target.copy(target);camera.up.set(0,0,-1);camera.position.set(target.x,target.y+Math.max(p.width,p.depth)*1.6,target.z+.001);camera.lookAt(target);controls.update();}else{camera.up.set(0,1,0);focusCamera();}}
function bindUi(){const upload=$('plan-files'),drop=$('drop-zone');upload.onchange=()=>setFiles(upload.files);for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('dragging');});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('dragging');});drop.addEventListener('drop',e=>setFiles(e.dataTransfer.files));$('generate').onclick=recognize;$('blank-project').onclick=startBlank;$('import-json').onclick=()=>$('json-file').click();$('json-file').onchange=async e=>{try{const text=await e.target.files[0].text();openProject(JSON.parse(text));}catch(error){toast(error.message);}};
  $('back-start').onclick=()=>{if(state.walk)exitWalk();$('editor-screen').hidden=true;$('start-screen').hidden=false;};$('export-json').onclick=downloadProject;$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('plan-view').onclick=()=>{showPlan(state.floor);$('plan-dialog').showModal();};$('close-plan').onclick=()=>$('plan-dialog').close();$('plan-dialog').onclick=e=>{if(e.target===$('plan-dialog'))$('plan-dialog').close();};
  $('add-room').onclick=addRoom;$('add-wall').onclick=addWall;$('add-furniture').onclick=addFurniture;document.querySelectorAll('[data-add-surface]').forEach(button=>button.onclick=()=>addSurface(button.dataset.addSurface));$('add-block').onclick=addBlock;$('undo-edit').onclick=undo;$('delete-selected').onclick=removeSelected;$('view-3d').onclick=()=>setView('3d');$('view-top').onclick=()=>setView('top');$('reset-camera').onclick=focusCamera;$('show-walls').onchange=e=>setDisplay('walls',e.target.checked);$('show-volumes').onchange=e=>setDisplay('volumes',e.target.checked);$('show-surfaces').onchange=e=>setDisplay('surfaces',e.target.checked);$('show-furniture').onchange=e=>setDisplay('furniture',e.target.checked);$('only-spaces').onclick=toggleOnlySpaces;$('level-mode').onclick=toggleLevelMode;$('show-labels').onchange=e=>{state.labels=e.target.checked;updateVisibility();};$('auto-rotate').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.target.classList.toggle('active',controls.autoRotate);};
  $('wall-height').oninput=e=>{state.wallHeight=Number(e.target.value);updateSection();};$('section-slider').oninput=e=>{state.section=Number(e.target.value);updateSection();};document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>{state.sectionAxis=b.dataset.axis;document.querySelectorAll('[data-axis]').forEach(x=>x.classList.toggle('active',x===b));updateSection();});$('reverse-section').onclick=e=>{state.reversed=!state.reversed;e.target.classList.toggle('active',state.reversed);updateSection();};document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>setPalette(b.dataset.palette));$('light-slider').oninput=e=>{const t=Number(e.target.value)/100;sun.intensity=.5+4*t;ambient.intensity=.8+2*t;};
  $('enter-walk').onclick=enterWalk;$('exit-walk').onclick=exitWalk;document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveWalk(b.dataset.move));$('eye-slider').oninput=e=>{state.eye=Number(e.target.value);updateWalkCamera();};$('fov-slider').oninput=e=>{camera.fov=Number(e.target.value);updateWalkCamera();};$('yaw-slider').oninput=e=>{state.yaw=Number(e.target.value);updateWalkCamera();};$('pitch-slider').oninput=e=>{state.pitch=Number(e.target.value);updateWalkCamera();};
  window.addEventListener('keydown',e=>{const typing=e.target.matches?.('input,textarea,select');if(e.key==='Escape'&&state.walk){exitWalk();return;}if(state.walk&&!typing){const move={w:'forward',ArrowUp:'forward',s:'back',ArrowDown:'back',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'}[e.key];if(move){e.preventDefault();moveWalk(move);return;}}if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}if((e.key==='Delete'||e.key==='Backspace')&&state.selection){e.preventDefault();removeSelected();}});
}

bindUi();checkAi();showContinue();
window.spatialEditor={getState:()=>({floor:state.floor,room:state.room,selection:state.selection,section:state.section,walk:state.walk,project:state.project}),openProject,createBlankProject,startBlank,setFloor,select,setView,enterWalk,exitWalk,undo,removeSelected};
